\" SPDX-License-Identifier: MIT
.Dd 2025-02-09
.Dt hexcat 1
.Sh NAME
.Nm hexcat
.Nd This line parsed for whatis database.

.Sh SYNOPSIS
.Nm
.Op Fl ncxvh
.Op Fl o Ar file
.Op Ar file

.Sh DESCRIPTION
.Nm
is an extremely small hex dumper.

.Sh OPTIONS
.Pp
Available flags and descriptions:
.Bl -tag -width -indent
.It Fl c
Colorize output.
.It Fl n
Don't colorize output.
.It Fl x
Suppress ASCII output.
.It Fl h
Print help message and exit.
.It Fl v
Print version information and exit.
.It Fl o Op file
The file to write output to.
.El
.Sh SEE ALSO
.Xr cat 1 ,
.Xr hexdump 1 ,
.Xr xxd 3
